name: "Build & scan container image"

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the image
      run: docker build . --file Dockerfile --tag juiceshop

# The mend dep scan should be called AFTER image build step
    - name: Mend CLI Download
      env:
        MEND_EMAIL: ${{secrets.MEND_EMAIL}}
        MEND_USER_KEY: ${{secrets.MEND_USER_KEY}}
        MEND_URL: https://saas.mend.io
      run: |
        echo === Downloading Mend CLI ==
        curl https://downloads.mend.io/cli/linux_amd64/mend -o /usr/local/bin/mend && chmod +x /usr/local/bin/mend
        echo === Mend CLI version: ===
        mend version

    - name: Mend CLI Scan
      env:
        MEND_EMAIL: ${{secrets.MEND_EMAIL}}
        MEND_USER_KEY: ${{secrets.MEND_USER_KEY}}
        MEND_URL: https://saas.mend.io
      run: |
        echo === Running Scan ===
        mend image juiceshop
      continue-on-error: true
